services:
  zmq_relay:
    build:
      context: ./zmq_relay
      dockerfile: Dockerfile
    container_name: zmq_relay
    environment:
      - GNB_TX=tcp://172.22.0.1:5000
      - SPOOFER_TX=tcp://zmq_ssb_spoof:7000
      - UE_REP=tcp://*:5100
      - SPOOFER_RX_REP=tcp://*:5101
    networks:
      rt_zmq:
        ipv4_address: 172.22.0.10
    restart: unless-stopped

networks:
  rt_zmq:
    external: true
    name: rt_zmq