{
 "title": "DCI sniffer",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Detected SCS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"rtusystem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"mib_sniffer_metric\" and\n    r._field == \"scs\"\n  )"
    }
   ]
  },
  {
   "title": "PDCCH Sample Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"rtusystem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"dci_sniffer_metric\" and\n    r._field == \"sample_time\"\n  )\n  |> window(every: 1s)\n    |> mean()\n    |> duplicate(column: \"_stop\", as: \"_time\")\n    |> window(every: inf)"
    }
   ]
  },
  {
   "title": "CFO by Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"rtusystem\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"mib_sniffer_metric\" and\n    r._field == \"cfo\"\n  ) |> movingAverage(n: 2)\n"
    }
   ]
  }
 ]
}