FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    TRANSFORMERS_CACHE=/app/huggingface_cache \
    HF_HOME=/app/huggingface_cache \
    TOKENIZERS_PARALLELISM=false

WORKDIR /app

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

#RUN pip install --upgrade --force-reinstall torch --index-url https://download.pytorch.org/whl/cu118

COPY . .

ENTRYPOINT ["sh", "-c", "python3 build_vector.py && python3 main.py --config /llm.yaml --log-level INFO"]
# ENTRYPOINT ["python3", "main.py", "--config", "/llm.yaml", "--log-level", "INFO"]
