processes:
  - type: "rtue"
    id: "rtue_zmq"
    config_file: "configs/zmq/ue_zmq_docker.conf"
    rf:
      type: "zmq"
      tcp_subnet: "172.22.0.0/24"
      gateway: "172.22.0.1"

  - type: "llm_worker"
    id: "llm_worker_1"
    config_file: "configs/llm/test.yaml"
    permissions:
      - sniffer
      - jammer
      - rtue
      - llm_worker
    rf:
      type: none