processes:
  - type: "llm_worker"
    id: "llm_worker_1"
    config_file: "configs/llm/test.yaml"
    permissions:
      - sniffer
      - jammer
      - rtue
      - llm_worker
      - uu-agent
    rf:
      type: none
    results_dir: llm_testing
