enable_cli: true

build_spec:
  - component: "cueltschey/sni5gect-compact"
    branch: "iq_file"
    pull: true

run_spec:
  - component: "cueltschey/sni5gect-compact"
    worker_thread: "sni5gect"
    name: "results_rectest_01"
    config_file: "configs/sni5gect/basic_file_test.yaml"
    rf:
      type: "none"
