enable_cli: false

build_spec:
  - component: "aevyy/signal-storm"
    image: "ghcr.io/oran-testing/sstorm"
    branch: "master"
    pull: false

run_spec:
  - component: "aevyy/signal-storm"
    worker_thread: "sstorm"
    name: "basic_zmq_signal_storm"
    config_file: "configs/srsran/sstorm_zmq_docker.conf"
    rf:
      type: "zmq"
      tcp_subnet: "172.22.0.0/24"
      gateway: "172.22.0.1"
