processes:
  - type: "uu_agent"
    id: "uu-agent"
    config_file: "configs/llm/test.yaml"
    permissions:
      - sniffer
      - jammer
      - rtue
      - llm_worker
      - uu-agent
    rf:
      images_dir: "/usr/share/uhd/images/"
      type: "zmq"
      tcp_subnet: "172.22.0.0/24"
      gateway: "172.22.0.1"


