injection_points = ["DU", "RU"]
pcap_dir = "Traffic/"
pcap_list = []
du = "enp5s0f1"
ru = "enp8s0f0np0"
attacker_dir = "/attack_env"
results_dir = "./attack_results"
duration_seconds   = 10                 
tcpreplay_topspeed = 1                           
tcpreplay_loop     = 0                       
keep_history="0"
